### ISSUE TITLE
Commit signing (for aqua registry) requires GPG keys, does not work with SSH keys

### ISSUE THREAD

**Issue by scop** [suzuki-shunsuke/oss-contribution-guide#77]
https://github.com/suzuki-shunsuke/oss-contribution-guide/blob/main/docs/commit-signing.md contains links that point to setting up various ways to sign commits. However, it appears that at least aqua-registry requires specifically GPG signing (e.g. SSH signing is not accepted), although that is not explicitly mentioned in https://aquaproj.github.io/docs/products/aqua-registry/contributing/#commit-signing or https://github.com/suzuki-shunsuke/oss-contribution-guide/blob/main/docs/commit-signing.md.

I've set up git to do SSH signing per https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key#telling-git-about-your-ssh-key (following links from the above commit-signing.md) but cmdx scaffolding in the registry just fails:

```
$ cmdx s daveshanley/vacuum
[...]
[ERROR] This repository requires commit signing, so please configure it.
        https://github.com/suzuki-shunsuke/oss-contribution-guide/blob/main/docs/commit-signing.md
exit status 1
```

If it's specifically GPG signing that's required, would be good to mention it.

However, it would be nice to support SSH signing, as most people likely have SSH and keys set up already, unlike GPG.

**Comment by suzuki-shunsuke** [comment]
Thank you for your feedback.
Oh, I didn't know commit signing other than GPG signing.

I'll look into other signing ways, and I'll fix the following validation.

https://github.com/aquaproj/aqua-registry/blob/541aa1f65f931f28fb8ff4ef7a247364718d40c8/scripts/check_gpgsign.sh#L5-L9

**Comment by suzuki-shunsuke** [comment]
About aqua-registry, you can disable the validation by comment out as a workaround.

```sh
# if [ "$(git config commit.gpgSign)" != true ]; then
#     echo "[ERROR] This repository requires commit signing, so please configure it." >&2
#     echo "        https://github.com/suzuki-shunsuke/oss-contribution-guide/blob/main/docs/commit-signing.md" >&2
#     exit 1
# fi
```

**Comment by suzuki-shunsuke** [comment]
I want to check if commit signing is configured before creating a commit because we enforce commit signing.
Should we check `user.signingkey` instead of `commit.gpgSign`? 🤔

```sh
if [ "$(git config user.signingkey)" != true ]; then
    echo "[ERROR] This repository requires commit signing, so please configure it." >&2
    echo "        https://github.com/suzuki-shunsuke/oss-contribution-guide/blob/main/docs/commit-signing.md" >&2
    exit 1
fi
```

**Comment by suzuki-shunsuke** [comment]
I've disabled the validation for now.

- https://github.com/aquaproj/aqua-registry/pull/29213

**Comment by scop** [comment]
Circling back to this, I'm not sure what happened when I initially filed the issue, sorry.

The option to sign commits with ssh is the same as with gpg (it uses ssh if `gpg.format` is set to `ssh`), so checking `config.gpgSign` as it used to be should be just fine and the aqua-registry PR that disabled it could be reverted.

**Comment by suzuki-shunsuke** [comment]
I see. Thank you.

I set up workflows to notify contributors.

e.g. https://github.com/aquaproj/aqua-registry/pull/32237#issuecomment-2661472896

<img width="585" alt="Image" src="https://github.com/user-attachments/assets/8c4efbb6-37dc-4dc1-9277-a79bd292cc9a" />

https://github.com/aquaproj/aqua-registry/blob/d0e96fbfc1943fc1fa4777a44be580b24fe69f87/.github/workflows/check-commit-signing.yaml
